repos:
  - repo: local
    hooks:
      - id: commit-msg-check
        name: Commit Message Check
        entry: python .git/hooks/commit-msg-check.py
        language: system
        stages: [commit-msg]
