name: Build Flask and Angular

on:
  push:
    branches:
      - main
      - feat/ci-implementation
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-flask:
    name: Build Flask Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          cd backend
          python -m pytest tests

  build-angular:
    name: Build Angular Frontend
    runs-on: ubuntu-latest
    needs: build-flask
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Angular app
        run: |
          cd frontend
          npm run build -- --configuration=production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: frontend/dist/
