name: Pylint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.13"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install pylint

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD/backend" >> $GITHUB_ENV  # Adds backend/ to PYTHONPATH

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files 'backend/*.py')
